import { _electron as electron, expect } from '@playwright/test'
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = path.resolve('../../trash/xmemeory-dev/topics-desktop')
mkdirSync(root, { recursive: true })
const profile = mkdtempSync(path.join(root, 'profile-'))
const env: Record<string, string> = { ...Object.fromEntries(Object.entries(process.env).filter((e): e is [string, string] => e[1] !== undefined)), XMEMEORY_TEST_DATA: profile }
delete env.ELECTRON_RUN_AS_NODE
const launch = () => electron.launch({ ...process.env.XMEMEORY_TEST_EXE ? { executablePath: process.env.XMEMEORY_TEST_EXE, args: [] } : { args: ['.'] }, env })
let app = await launch()
try {
  let page = await app.firstWindow()
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.locator('nav button').filter({ hasText: '选题' }).click()
  const input = page.getByRole('textbox', { name: '新选题标题' })
  await input.fill('  '); await input.press('Enter')
  expect((await page.evaluate(() => window.xm.snapshot())).notes).toHaveLength(0)
  await input.fill('长文甲'); await input.press('Enter')
  await expect(page.getByRole('textbox', { name: '标题', exact: true })).toHaveValue('长文甲')
  await expect(page.locator('.tiptap')).toContainText('大纲')
  await expect(page.locator('.tiptap')).toContainText('长文')
  await input.fill('长文乙'); await input.press('Enter')
  await expect(page.getByRole('textbox', { name: '标题', exact: true })).toHaveValue('长文乙')
  await input.fill('长文丙'); await input.press('Enter')
  await expect(page.locator('.topic-row button')).toHaveText(['长文丙', '长文乙', '长文甲'])
  await page.getByRole('button', { name: '长文乙', exact: true }).click()
  await page.getByRole('button', { name: '切换 Markdown 源码' }).click()
  const body = '## 大纲\n\n1. 核心论点\n\n## 长文\n\n正文独特检索词\n\n| 项目 | 内容 |\n| --- | --- |\n| A | B |\n\n[[长文甲]]\n'
  await page.getByRole('textbox', { name: 'Markdown 源码' }).fill(body)
  // Complete immediately: flush must preserve the edit before changing status.
  await page.getByRole('checkbox', { name: '标记 长文乙 已写完' }).check()
  await expect(page.locator('.topic-row button')).toHaveText(['长文丙', '长文甲', '长文乙'])
  await expect(page.locator('.topic-row.completed button')).toHaveCSS('text-decoration-line', 'line-through')
  let snapshot = await page.evaluate(() => window.xm.snapshot())
  let note = snapshot.notes.find(n => n.title === '长文乙')!
  expect(note.body).toBe(body)
  expect(note.completed).toBe(true)
  expect(note.path).toMatch(/^topics\//)
  await page.getByRole('button', { name: '切换 Markdown 源码' }).click()
  await expect(page.locator('.tiptap table')).toContainText('A')
  await page.locator('.wiki-link').filter({ hasText: '长文甲' }).click()
  await expect(page.getByRole('textbox', { name: '标题', exact: true })).toHaveValue('长文甲')
  await page.getByRole('button', { name: '长文乙', exact: true }).click()
  await page.screenshot({ path: path.join(profile, 'topics.png') })
  await app.close(); app = await launch(); page = await app.firstWindow()
  page.on('pageerror', e => errors.push(e.message))
  await page.locator('nav button').filter({ hasText: '选题' }).click()
  await expect(page.getByRole('checkbox', { name: '标记 长文乙 已写完' })).toBeChecked()
  await page.getByRole('button', { name: '长文乙', exact: true }).click()
  await expect(page.locator('.tiptap')).toContainText('正文独特检索词')
  const file = path.join(snapshot.library, note.path)
  writeFileSync(file, readFileSync(file, 'utf8').replace('completed: true', 'completed: false').replace('正文独特检索词', '外部编辑检索词'))
  await expect(page.locator('.tiptap')).toContainText('外部编辑检索词', { timeout: 8000 })
  await expect(page.getByRole('checkbox', { name: '标记 长文乙 已写完' })).not.toBeChecked()
  await expect(page.locator('.topic-row button')).toHaveText(['长文丙', '长文乙', '长文甲'])
  await page.getByRole('button', { name: '搜索所有内容' }).click()
  await page.getByPlaceholder('搜索灵感、记忆、选题和候选稿…').fill('外部编辑检索词')
  await page.getByRole('combobox', { name: '内容类型' }).selectOption('topic')
  await expect(page.locator('.note-card')).toHaveCount(1)
  await page.locator('.note-card').click()
  await page.getByRole('button', { name: '移到回收站' }).click()
  await expect(page.locator('.note-card')).toHaveCount(0)
  await page.getByRole('button', { name: '回收站', exact: true }).click()
  await page.locator('.note-card').click()
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await page.locator('nav button').filter({ hasText: '选题' }).click()
  await expect(page.locator('.topic-row button')).toHaveText(['长文丙', '长文乙', '长文甲'])
  await page.getByRole('checkbox', { name: '标记 长文丙 已写完' }).check()
  await page.getByRole('checkbox', { name: '标记 长文丙 已写完' }).uncheck()
  await page.getByRole('button', { name: '新选题', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '标题', exact: true })).toHaveValue('未命名选题')
  await page.locator('.tiptap').click()
  await app.evaluate(async ({ clipboard, nativeImage, ClipboardItem }) => {
    const png = nativeImage.createFromBitmap(Buffer.alloc(80 * 60 * 4, 255), { width: 80, height: 60 }).toPNG()
    await clipboard.write([new ClipboardItem({ 'image/png': new Blob([new Uint8Array(png)], { type: 'image/png' }) })])
  })
  await page.keyboard.press('Control+V')
  const image = page.locator('.tiptap img.local-image')
  await expect(image).toBeVisible()
  await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(80)
  await expect(page.locator('.save-status')).toContainText('已保存到本地')
  await image.dblclick()
  await expect(page.getByRole('dialog', { name: '图片预览' })).toBeVisible()
  await page.getByRole('button', { name: '复制图片', exact: true }).click()
  await expect(page.getByText('已复制图片', { exact: true })).toBeVisible()
  expect(await app.evaluate(async ({ clipboard }) => clipboard.has('image/png'))).toBe(true)
  await page.keyboard.press('Escape')
  await page.evaluate(() => window.xm.settings({ theme: 'dark' }))
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.screenshot({ path: path.join(profile, 'topics-dark.png') })
  snapshot = await page.evaluate(() => window.xm.snapshot())
  expect(snapshot.notes.every(n => n.kind === 'topic')).toBe(true)
  expect(snapshot.conflicts).toHaveLength(0)
  expect(errors).toEqual([])
  console.log('PASS: 选题创建、空标题、稳定排序、勾选前保存、划线、Markdown 表格与双链、重启、外部回读、搜索、删除恢复、新选题入口、粘贴图片与大图复制、深色主题，无页面错误')
  console.log(`截图：${path.join(profile, 'topics.png')}`)
} finally { await app.close() }
