import { _electron as electron, expect } from '@playwright/test'
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { dateKey } from '../src/shared/calendar'
const temporary=path.resolve('../../trash/xmemeory-dev/calendar-desktop');mkdirSync(temporary,{recursive:true})
const userData=mkdtempSync(path.join(temporary,'profile-'))
const env: Record<string,string>={...Object.fromEntries(Object.entries(process.env).filter((e):e is [string,string]=>e[1]!==undefined)),XMEMEORY_TEST_DATA:userData};delete env.ELECTRON_RUN_AS_NODE
const launch=()=>electron.launch({...process.env.XMEMEORY_TEST_EXE?{executablePath:process.env.XMEMEORY_TEST_EXE,args:[]}:{args:['.']},env})
let app=await launch()
try {
  let page=await app.firstWindow();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await expect(page.getByRole('heading',{name:'这一周的灵感'})).toBeVisible()
  await expect(page.locator('.calendar-day')).toHaveCount(7)
  const today=dateKey();const visibleDays=await page.locator('.calendar-day').evaluateAll(days=>days.map(day=>day.getAttribute('aria-label')!));const otherDay=visibleDays.find(date=>date!==today)!
  await page.locator(`section[aria-label="${otherDay}"] .day-heading`).click()
  await page.getByRole('button',{name:'新灵感',exact:true}).click()
  let created=(await page.evaluate(()=>window.xm.snapshot())).notes.find(n=>n.title==='未命名灵感')!
  expect(created.scheduledDate).toBe(today)
  await page.getByRole('button',{name:'← 返回日历',exact:true}).click()
  const input=page.getByRole('textbox',{name:`${today} 新灵感标题`})
  await input.fill('  ');await input.press('Enter')
  expect((await page.evaluate(()=>window.xm.snapshot())).notes.length).toBe(1)
  await input.fill('周历快速灵感');await input.press('Enter')
  await expect(page.getByRole('button',{name:'周历快速灵感',exact:true})).toBeVisible()
  await input.fill('第二条灵感');await input.press('Enter')
  await input.fill('第三条灵感');await input.press('Enter')
  await page.getByRole('button',{name:'拖动 第三条灵感 调整顺序或日期'}).dragTo(page.getByRole('button',{name:'拖动 未命名灵感 调整顺序或日期'}))
  await expect(page.locator(`section[aria-label="${today}"] .calendar-entry`).first()).toContainText('第三条灵感')
  await page.getByRole('button',{name:'拖动 第二条灵感 调整顺序或日期'}).dragTo(page.locator(`section[aria-label="${otherDay}"] .quick-create`))
  await expect(page.locator(`section[aria-label="${otherDay}"]`).getByRole('button',{name:'第二条灵感',exact:true})).toHaveCount(1)
  await expect(page.locator(`section[aria-label="${today}"]`).getByRole('button',{name:'第二条灵感',exact:true})).toHaveCount(0)
  await page.getByRole('checkbox',{name:'标记 周历快速灵感 已使用'}).check()
  await expect(page.locator('.calendar-entry.completed')).toContainText('周历快速灵感')
  const snapshot=await page.evaluate(()=>window.xm.snapshot());const note=snapshot.notes.find(n=>n.title==='周历快速灵感')!
  expect(note.scheduledDate).toBe(dateKey())
  expect(snapshot.notes.find(n=>n.title==='第三条灵感')?.sortOrder).toBe(0)
  await page.screenshot({path:path.join(temporary,'week.png')})
  await app.close();app=await launch();page=await app.firstWindow()
  await expect(page.locator(`section[aria-label="${today}"] .calendar-entry`).first()).toContainText('第三条灵感')
  await expect(page.locator(`section[aria-label="${otherDay}"]`).getByRole('button',{name:'第二条灵感',exact:true})).toHaveCount(1)
  await expect(page.getByRole('checkbox',{name:'标记 周历快速灵感 已使用'})).toBeChecked()
  await page.getByRole('checkbox',{name:'标记 周历快速灵感 已使用'}).uncheck()
  await page.getByLabel('选择月份').fill('2024-02')
  await expect(page.getByRole('heading',{name:'这个月的灵感'})).toBeVisible()
  const leap=page.getByRole('textbox',{name:'2024-02-29 新灵感标题'})
  await leap.fill('闰日灵感');await leap.press('Enter')
  await expect(page.getByRole('button',{name:'闰日灵感',exact:true})).toBeVisible()
  await page.screenshot({path:path.join(temporary,'month.png')})
  await page.getByRole('button',{name:'闰日灵感',exact:true}).click()
  const body=page.locator('.tiptap')
  await body.click();await body.pressSequentially('[tes](https://www.baidu.com)',{delay:15})
  await expect(body.getByRole('link',{name:'tes',exact:true})).toHaveAttribute('href','https://www.baidu.com')
  await page.getByRole('button',{name:'插入链接',exact:true}).click()
  await page.getByRole('textbox',{name:'链接文字'}).fill('测试地址')
  await page.getByRole('textbox',{name:'链接地址'}).fill('baidu')
  await page.getByRole('button',{name:'插入',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('完整网址')
  await page.getByRole('textbox',{name:'链接地址'}).fill('example.com')
  await page.getByRole('button',{name:'插入',exact:true}).click()
  await expect(body.getByRole('link',{name:'测试地址'})).toHaveAttribute('href','https://example.com/')
  await page.getByRole('button',{name:/^加入创作素材/}).click()
  await expect(page.locator('.material-list')).toContainText('闰日灵感')
  await page.getByRole('button',{name:'关闭创作面板'}).click()
  await page.getByRole('button',{name:/^已加入创作素材/}).click()
  await expect(page.locator('.material-list button')).toHaveCount(1)
  await expect(page.getByRole('button',{name:'生成候选稿'})).toBeDisabled()
  await page.locator('.material-list button').click()
  await expect(page.locator('.material-list button')).toHaveCount(0)
  await page.getByRole('button',{name:'关闭创作面板'}).click()
  await page.getByRole('button',{name:'← 返回日历',exact:true}).click()
  await expect(page.getByLabel('选择月份')).toHaveValue('2024-02')
  await page.getByRole('button',{name:'闰日灵感',exact:true}).click()
  await expect(page.getByRole('link',{name:'tes',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'← 返回日历',exact:true}).click()
  const leapNote=(await page.evaluate(()=>window.xm.snapshot())).notes.find(n=>n.title==='闰日灵感')!
  const file=path.join(snapshot.library,leapNote.path)
  writeFileSync(file,readFileSync(file,'utf8').replace('2024-02-29','2024-02-28').replace('completed: false','completed: true'))
  await expect(page.locator('section[aria-label="2024-02-28"] .completed')).toContainText('闰日灵感',{timeout:10000})
  expect(errors).toEqual([])
  console.log('PASS: 周/月日历、闰日、快速创建、完成撤销、重启、外部状态回读、手动链接/链接表单、创作素材反馈去重移除')
} finally {await app.close()}
